openapi: '3.0.3'
info:
  title: Praktek rest Api
  version: '1.0'
servers:
  - url: http://localhost:3000/v1
components:
  schemas:
    user:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        age:
          type: integer
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

paths:
  /users:
    get:
      operationId: getUsers
      description: end point untuk mendapat semua user
      parameters: []
      responses:
        '200':
          description: Berhasil
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'
        '500':
          description: server gagal
        '403':
          description: tidak di ijinkan
  /user/{id}:
    get:
      operationId: getUserById
      description: endpoint untuk mendapatkan user sesuai id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Berhasil
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'
        '500':
          description: server gagal
        '403':
          description: akses ditolak/tidak di ijinkan
    delete:
      operationId: deleteUserById
      description: end point untuk menghapus user berdasarkan id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Berhasil
        '500':
          description: server gagal
        '403':
          description: akses ditolak/tidak di ijinkan
    put:
      operationId: updateUserById
      description: endpoint untuk mengubah data user bedasarkan id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                age:
                  type: integer
              required:
                - name
                - email
                - age
      responses:
        '200':
          description: Berhasil
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'
  /user:
    post:
      operationId: createUser
      description: endpoint untuk membuat user baru
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                age:
                  type: integer
              required:
                - name
                - email
                - age
      responses:
        '200':
          description: Berhasil
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'
        '500':
          description: server gagal
        '403':
          description: akses ditolak/tidak di ijinkan
