openapi: '3.0.3'
info:
  title: Praktek rest Api
  version: '1.0'
servers:
  - url: http://localhost:3000
components:
  schemas:
    user:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        age:
          type: integer
        creatdAt:
          type: string
        updatedAt:
          type: string

paths:
  /users:
    get:
      operationId: getUsers
      description: end point untuk mendapat semua user
      parameters: []
      responses:
        '200':
          description: Berhasil
          content:
            aplication/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'
        '500':
          description: server gagal
        '403':
          description: tidak di ijinkan
  /user/{id}:
    get:
      operationId: getUserById
      description: endpoint untuk mendapatkan user sesuai id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Berhasil
          content:
            aplication/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'
        '500':
          description: server gagal
        '403':
          description: akses ditolak/tidak di ijinkan
    delete:
      operationId: deleteUserById
      description: end point untuk menghapus user berdasarkan id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Berhasil
        '500':
          description: server gagal
        '403':
          description: akses ditolak/tidak di ijinkan
    put:
      operationId: updateUserById
      description: endpoint untuk mengubah data user bedasarkan id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: name
          in: path
          required: true
          schema:
            type: string
        - name: email
          in: path
          required: true
          schema:
            type: string
        - name: age
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Berhasil
          content:
            aplication/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'
